### PR TITLE
Fix Search Page & Results

### LINKED ISSUE #108: Clicking on search Data button takes you to blank data by topic
We should not se the id on the hash since data by topic uses that to navigate between sections. Lets use `indicatorId` as the rest do in the `query string`.

## Reproduce:
Clicking on this:
Screen Shot 2020-03-11 at 9 11 11 AM

Takes you to this:
Screen Shot 2020-03-11 at 9 09 39 AM

https://www.pivotaltracker.com/story/show/171744631

cc @KhadijaMahanga @kilemensi

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description
- Add language to Search Page
- Slice multi-language data

Resolves #108

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/utils/sliceMultiLangData.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+export default function sliceMultiLangData(title, lang) {
+  const searchTerm = `[:${lang}]`;
+  const langIndex = title.indexOf(searchTerm);
+  if (langIndex !== -1) {
+    const startIndex = langIndex + searchTerm.length;
+    const endIndex = title.indexOf('[:', startIndex);
+
+    return title.slice(startIndex, endIndex);
+  }
+  return title;
```
Comment (karimkawambwa) [inline src/utils/sliceMultiLangData.js]: title should be renamed to value since it could be anything  just to keep the naming conventions

File: src/components/Navigation/SearchDrawer.js [hunk 2]
```diff
@@ -245,21 +252,12 @@ function SearchDrawer({ children, active, toggle }) {
...
-                                title={suggestion.value}
-                                placement="bottom-start"
-                                classes={{ tooltip: classes.tooltip }}
-                              >
-                                <Typography color="textSecondary" noWrap>
-                                  {suggestion.value}
-                                </Typography>
-                              </Tooltip>
-                            </Link>
+                              {suggestion.label}
```
Comment (kilemensi) [inline src/components/Navigation/SearchDrawer.js]: `Tooltip` is still needed for when the suggestion is too long to fit:
Screenshot from 2020-03-11 15-42-58

File: src/components/SearchInput/Input.js [hunk 3]
```diff
@@ -48,9 +48,13 @@ function Input({ onRefresh, placeholder, query }) {
       // API. On all other pages that this component is used, onRefresh is
       // expected to be null
       if (typeof onRefresh === 'function') {
-        router.push(`/search?q=${searchTerm}`, `/search?q=${searchTerm}`, {
-          shallow: true
-        });
+        router.push(
+          `/search?q=${searchTerm}&lang=${language}`,
+          `/search?q=${searchTerm}&lang=${language}`,
```
Comment (kilemensi) [inline src/components/SearchInput/Input.js]:
```suggestion
          undefined,
```

Since they're the same, `undefined` should do the trick: https://nextjs.org/docs/api-reference/next/router#routerpush

File: src/components/SearchResults/DataSearchResultItem.js [hunk 4]
```diff
@@ -168,7 +179,7 @@ function InGeographyDataResult({ item, title, chartId, inGeographies }) {
       </Grid>
       <Link
         href={href}
-        as={`/profiles/${geo.geoLevel}-${geo.geoCode}#${chartId}`}
+        as={`/profiles/${geo.geoLevel}-${geo.geoCode}?lang=${language}#${chartId}`}
```
Comment (kilemensi) [inline src/components/SearchResults/DataSearchResultItem.js]:
```suggestion
        as={`/profiles/${geo.geoLevel}-${geo.geoCode}?lang=${language}&indicatorId=${chartId}`}
```

Comment (karimkawambwa) [reply src/components/SearchResults/DataSearchResultItem.js]: @kilemensi 

Resolves #108 

https://www.pivotaltracker.com/story/show/171744631

Comment (karimkawambwa) [reply src/components/SearchResults/DataSearchResultItem.js]: cc @KhadijaMahanga
